### PR TITLE
XSpec integration, continued

### PR DESCRIPTION
**Pull request by wendellpiez**
# Committer Notes

Now with XSpec support including XSpec for XSLT, Schematron and XQuery.

With batching capabilities plus a CI/CD runtime harness. Also, an XProc step that can accept any XSpec without prior knowledge of its test target type: they can effectively be mixed.

### All Submissions:

- [ ] Follow [Contributing](https://github.com/usnistgov/oscal-xproc3/blob/main/CONTRIBUTING.md) guidelines
- [ ] Make no changes duplicating or conflicting with other open [Pull Requests](https://github.com/usnistgov/oscal-xproc3/pulls)
- [ ] Have been squashed to keep only relevant interim commits, if any \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have been tested manually
- [ ] Pass all CI/CD checks

### Changes to Core Features:

- [ ] The Issue history, discussions and new documentation provide context for new features -- everything is reasonably self-explanatory
- [ ] New tests are included
- [ ] New examples are included
- [ ] Everything in readme and TESTING documents has been updated

### CODE REVIEW

**Comment by wendellpiez** [comment]
@galtm and other reviewers, this PR supersedes #5 and #8.

Under CI/CD so far we have just one XSpec with two tests. This is set up in the file [testing/TEST-XSPEC-SET.xpl](testing/TEST-XSPEC-SET.xpl). Thanks!

**Comment by galtm** [comment]
> ## XSpec Test Results
> 2 tests  ±0   2 ✅ ±0   0s ⏱️ ±0s 1 suites ±0   0 💤 ±0  1 files   ±0   0 ❌ ±0 
> 
> Results for commit [2497040](https://github.com/usnistgov/oscal-xproc3/commit/24970403f1ee74e43b4fc1f3642e40b0eedec1b5). ± Comparison against base commit [ff8255d](https://github.com/usnistgov/oscal-xproc3/commit/ff8255d8706e38b9dead80bc14cb3f87ceb256e3).

Is there supposed to be a link to a page that shows which tests were run and maybe the log details?

**Review by galtm — APPROVED** [review]
You said this PR supersedes #5 but that's where the lines of code were that I wanted to comment on, so I put my comments there. Thanks!

**Comment by wendellpiez** [comment]
Tests run under CI/CD now include running three different XSpecs, one each for XSLT, XQuery and Schematron, demonstrating capability.

Files in the `testing` directory configure which XSpecs are run, and which XProc files are Schematron-validated.

**Pull request merged**
